services:
  backend-flask:
    env_file:
      - ./backend-flask/.env
    build: ./backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    env_file:
      - ./frontend-react-js/.env
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
  post:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=cruddur
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5436:5432'
    volumes: 
      - post:/var/lib/postgresql/data
      - ./backend-flask/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
   
volumes:
  post:
    driver: local
